name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - prod #trigger when push to branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Hostinger VPS
        run: |
          ssh -o StrictHostKeyChecking=no user@147.79.68.107 << 'EOF'
            cd /path/to/your/project
            git pull origin main
            # Any other deployment steps (e.g., restart server, run build)
          EOF

